### ISSUE TITLE
No module named 'yamlinclude'

### ISSUE THREAD

**Issue by alexsalex** [n0bel/PiClock3#10]
```
pi@PyClock:~/PiClock3 $ python3 ./PyQtPiClock3.py
Traceback (most recent call last):
  File "/home/pi/PiClock3/./PyQtPiClock3.py", line 6, in <module>
    from PiClock3.PiClock3 import PiClock3
  File "/home/pi/PiClock3/PiClock3/PiClock3.py", line 5, in <module>
    from yamlinclude import YamlIncludeConstructor
ModuleNotFoundError: No module named 'yamlinclude'
```

**Comment by SerBrynden** [comment]
Did you install all the required packages according to the readme? -> https://github.com/n0bel/PiClock3#:~:text=No%20detailed%20instructions%20have%20been%20created.%20Basic%20information%20follows.

**Comment by gamename** [comment]
@SerBrynden 
I installed the pre-reqs and got the same error.

**Comment by SerBrynden** [comment]
PiClock3 isn't finished anyway.  Try using https://github.com/SerBrynden/PiClock

**Comment by gamename** [comment]
> PiClock3 isn't finished anyway. Try using https://github.com/SerBrynden/PiClock

Thanks @SerBrynden!

**Comment by n0bel** [comment]
Fixed. There was never a `requirements.txt`, so the dependencies were undocumented and you had to guess at them.

There is one now, from PR #8: tzlocal, metar, astral, pyyaml-include, compassheadinglib. `pip install -r requirements.txt` should sort it.

**Comment by n0bel** [comment]
Correction to my last comment, and apologies for the noise.

The `requirements.txt` I pointed you at pinned `pyyaml-include~=2.2.0`, and 2.x renamed the module from `yamlinclude` to `yaml_include` and changed the API. `Config.py` imports `YamlIncludeConstructor` from `yamlinclude`, so following that file would have failed for you in a very similar way to the original problem.

That's fixed properly now — it pins back to `pyyaml-include>=1.3,<2`, which is what the code actually expects. Verified on Python 3.9.2: 1.3.2 installs and the import works.

Two other pins were wrong in the same way and are also fixed: tzlocal 5.4 and metar 2.0 both require Python 3.10, which quietly dropped Raspberry Pi OS Bullseye. Neither was needed by the code.

`pip install -r requirements.txt` should behave this time.
